# Generated by Django 5.0.4 on 2024-07-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantID', '0002_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
